<a href="https://colab.research.google.com/github/kartikayladdha/NLP/blob/main/Labs/Lab5/NLP_5_Spam_Classification_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import nltk as nltk
# import gensim as gs
# import spacy as sp
# import textblob as tb
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import nltk
nltk.download('stopwords')
nltk.download('punkt')
from nltk.corpus import stopwords
from string import punctuation
from nltk.tokenize import word_tokenize
from nltk.stem import LancasterStemmer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df = pd.read_csv('spam.csv', engine='python')
df.head()

v1  ... Unnamed: 4
0   ham  ...        NaN
1   ham  ...        NaN
2  spam  ...        NaN
3   ham  ...        NaN
4   ham  ...        NaN

[5 rows x 5 columns]

In [ ]:
df1 = df[['v1', 'v2']]
df1.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df1['v1'].value_counts()

ham     4825
spam     747
Name: v1, dtype: int64

In [ ]:
df1= df1.dropna()
df1.shape

(5572, 2)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df1['v1'] = le.fit_transform(df1['v1'])

In [ ]:
value_counts = df1['v1'].value_counts()
value_counts

0    4825
1     747
Name: v1, dtype: int64

In [ ]:
from string import punctuation
from nltk.corpus import stopwords
stuff_to_be_removed = list(stopwords.words('english'))+list(punctuation)
from nltk.tokenize import word_tokenize
from nltk.stem import LancasterStemmer
stemmer = LancasterStemmer()
corpus = df1['v2'].tolist()
len(corpus)
corpus = corpus[1:] #for demonstration, taking less data

In [ ]:
final_corpus = []
for i in range(len(corpus)):
  word = word_tokenize(corpus[i].lower())
  word = [stemmer.stem(y) for y in word if y not in stuff_to_be_removed]
  j = " ".join(word)
  final_corpus.append(j)
#final_corpus

In [ ]:
final_corpus

['ok lar ... jok wif u on ...',
 "fre entry 2 wkly comp win fa cup fin tkts 21st may 2005. text fa 87121 receiv entry quest std txt rat c 's apply 08452810075over18 's",
 'u dun say ear hor ... u c already say ...',
 "nah n't think goe usf liv around though",
 "freemsg hey darl 's 3 week 's word back 'd lik fun stil tb ok xxx std chgs send �1.50 rcv",
 'ev broth lik speak tre lik aid pat',
 "per request 'melle mel oru minnaminungint nurungu vettam set callertun cal press *9 cop friend callertun",
 'win valu network custom select receive �900 priz reward claim cal 09061701461. claim cod kl341 valid 12 hour',
 'mobl 11 month u r entitl upd latest colo mobl camer fre cal mobl upd co fre 08002986030',
 "'m gon na hom soon n't want talk stuff anym tonight k 've cri enough today",
 'six chant win cash 100 20,000 pound txt csh11 send 87575. cost 150p/day 6days 16+ tsandc apply reply hl 4 info',
 'urg 1 week fre memb �100,000 priz jackpot txt word claim 81010 c www.dbuk.net lccltd pobox 4403ld

In [ ]:
label_list=df1['v1'].tolist()
label_list=label_list[1:]
newdf = pd.DataFrame(final_corpus)
newdf['label'] = label_list
newdf.columns=['message','label']
newdf.head()

message  label
0                        ok lar ... jok wif u on ...      0
1  fre entry 2 wkly comp win fa cup fin tkts 21st...      1
2          u dun say ear hor ... u c already say ...      0
3            nah n't think goe usf liv around though      0
4  freemsg hey darl 's 3 week 's word back 'd lik...      1

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
vector = tfidf.fit_transform(newdf['message'])
x_train = vector.toarray()
print(x_train)
y_train= newdf['label']

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
from sklearn.naive_bayes import MultinomialNB
ab = MultinomialNB()
ab.fit(x_train,y_train)
ypred = ab.predict(x_train)
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_train,ypred))
print(confusion_matrix(y_train,ypred))
print(classification_report(y_train,ypred))

0.982049901274457
[[4824    0]
 [ 100  647]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      4824
           1       1.00      0.87      0.93       747

    accuracy                           0.98      5571
   macro avg       0.99      0.93      0.96      5571
weighted avg       0.98      0.98      0.98      5571



In [ ]:
from sklearn.svm import LinearSVC

svc = LinearSVC().fit(x_train,y_train)

y_pred = svc.predict(x_train)

print(accuracy_score(y_train,y_pred))

print(confusion_matrix(y_train,y_pred))

print(classification_report(y_train,y_pred))

0.9991024950637228
[[4822    2]
 [   3  744]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4824
           1       1.00      1.00      1.00       747

    accuracy                           1.00      5571
   macro avg       1.00      1.00      1.00      5571
weighted avg       1.00      1.00      1.00      5571

